### ISSUE TITLE
Installation instructions for Windows are becoming outdated

### ISSUE THREAD

**Issue by mikron-ia** [larmo-hub/larmo-webapp#12]
Recently (around version 1.8.1), Docker for Windows moved from using `boot2docker` (now considered deprecated) to more universal (but also less intuitive and out-of-the-box) `docker-machine`. Instructions have to be updated (or actually expanded, as some people still use older versions).

**Comment by adrianpietka** [comment]
Updated. Commit @fcb1dfa .
